"""Integration tests for HTML report generation."""

import unittest
import tempfile
import os
from pathlib import Path
from datetime import datetime

from scriptplan.parser.tjp_parser import ProjectFileParser
from scriptplan.report.report import Report, ReportFormat, ReportType
from scriptplan.core.project import Project


class TestHtmlReportIntegration(unittest.TestCase):
    """Integration tests for HTML report generation."""

    @classmethod
    def setUpClass(cls):
        """Parse the tutorial file once for all tests."""
        parser = ProjectFileParser()
        # Find the test data directory
        test_data_dir = Path(__file__).parent / 'data'
        tutorial_path = test_data_dir / 'tutorial.tjp'
        with open(tutorial_path, 'r') as f:
            text = f.read()
        cls.project = parser.parse(text)

    def test_journal_entries_in_project(self):
        """Verify journal entries are included in the project."""
        journal = self.project.attributes.get('journal')
        self.assertIsNotNone(journal, "Project should have a journal")
        self.assertGreater(len(journal), 0, "Journal should have entries")


class TestHtmlDocumentBuilding(unittest.TestCase):
    """Test HTML document building with build_html_document."""

    def test_build_document_with_content(self):
        """Test building a complete HTML document."""
        from scriptplan.report.html_generator import build_html_document

        html = build_html_document(
            title="Test Report",
            content="<table><tr><td>Data</td></tr></table>",
            project_name="Test Project",
            subtitle="2023-01-01 - 2023-12-31"
        )

        # Verify basic HTML structure
        self.assertIn('<!DOCTYPE html>', html)
        self.assertIn('<html lang="en">', html)
        self.assertIn('<head>', html)
        self.assertIn('<body>', html)
        self.assertIn('</html>', html)

        # Verify CSS is included
        self.assertIn('<style>', html)
        self.assertIn('--tj-primary', html)

        # Verify content
        self.assertIn('Test Project', html)
        self.assertIn('2023-01-01 - 2023-12-31', html)
        self.assertIn('<table><tr><td>Data</td></tr></table>', html)

    def test_build_document_with_navigation(self):
        """Test building HTML with navigation."""
        from scriptplan.report.html_generator import build_html_document

        nav = [
            {'title': 'Tasks', 'url': 'tasks.html', 'active': True},
            {'title': 'Resources', 'url': 'resources.html', 'active': False}
        ]

        html = build_html_document(
            title="Task Report",
            content="<p>Task content</p>",
            project_name="Project",
            navigation=nav
        )

        self.assertIn('tj_navigation', html)
        self.assertIn('tasks.html', html)
        self.assertIn('resources.html', html)
        self.assertIn('class="active"', html)

    def test_build_document_with_footer(self):
        """Test that HTML includes footer."""
        from scriptplan.report.html_generator import build_html_document

        html = build_html_document(
            title="Test",
            content="<p>Content</p>",
            footer=True
        )

        self.assertIn('tj_page_footer', html)
        self.assertIn('Generated by ScriptPlan', html)

    def test_build_document_without_footer(self):
        """Test that HTML can be built without footer."""
        from scriptplan.report.html_generator import build_html_document

        html = build_html_document(
            title="Test",
            content="<p>Content</p>",
            footer=False
        )

        self.assertNotIn('Generated by ScriptPlan', html)


class TestTableReportHtml(unittest.TestCase):
    """Test table report HTML generation."""

    def test_report_table_to_html(self):
        """Test that ReportTable produces valid HTML."""
        from scriptplan.report.table_report import (
            ReportTable, ReportTableLine, ReportTableCell, Alignment
        )

        # Create a simple table
        table = ReportTable()

        # Header row
        header = ReportTableLine()
        header.add_cell(ReportTableCell(text='Name', is_header=True))
        header.add_cell(ReportTableCell(text='Start', is_header=True, alignment=Alignment.CENTER))
        header.add_cell(ReportTableCell(text='End', is_header=True, alignment=Alignment.CENTER))
        table.add_header_line(header)

        # Data row
        row = ReportTableLine()
        row.add_cell(ReportTableCell(text='Task 1'))
        row.add_cell(ReportTableCell(text='2023-01-01', alignment=Alignment.CENTER))
        row.add_cell(ReportTableCell(text='2023-06-30', alignment=Alignment.CENTER))
        table.add_body_line(row)

        # Generate HTML
        html = table.to_html()

        self.assertIn('<table', html)
        self.assertIn('tj_report_table', html)
        self.assertIn('<thead>', html)
        self.assertIn('<tbody>', html)
        self.assertIn('<th>Name</th>', html)
        self.assertIn('<td>Task 1</td>', html)

    def test_table_to_csv(self):
        """Test that ReportTable produces valid CSV."""
        from scriptplan.report.table_report import (
            ReportTable, ReportTableLine, ReportTableCell
        )

        table = ReportTable()

        # Header
        header = ReportTableLine()
        header.add_cell(ReportTableCell(text='Name'))
        header.add_cell(ReportTableCell(text='Value'))
        table.add_header_line(header)

        # Data
        row = ReportTableLine()
        row.add_cell(ReportTableCell(text='Item 1'))
        row.add_cell(ReportTableCell(text='100'))
        table.add_body_line(row)

        csv_data = table.to_csv()

        self.assertEqual(len(csv_data), 2)
        self.assertEqual(csv_data[0], ['Name', 'Value'])
        self.assertEqual(csv_data[1], ['Item 1', '100'])


class TestHtmlGeneratorInReport(unittest.TestCase):
    """Test html_generator module integration."""

    def test_import_in_report(self):
        """Verify html_generator is properly imported in report.py."""
        from scriptplan.report.report import (
            build_html_document,
            get_default_css
        )
        self.assertIsNotNone(build_html_document)
        self.assertIsNotNone(get_default_css)

    def test_build_html_document_callable(self):
        """Verify build_html_document is callable from report module."""
        from scriptplan.report.report import build_html_document

        html = build_html_document(
            title="Test",
            content="<p>Test content</p>"
        )
        self.assertIn("<!DOCTYPE html>", html)


if __name__ == '__main__':
    unittest.main()
