"""Tests for HTML report generation."""

import unittest
from datetime import datetime

from rodmena_resource_management.report.html_generator import (
    get_default_css,
    build_html_document,
    format_date,
    format_duration,
    format_percentage,
    alert_indicator_html,
    journal_entry_html
)


class TestGetDefaultCSS(unittest.TestCase):
    def test_returns_css_string(self):
        css = get_default_css()
        self.assertIsInstance(css, str)
        self.assertGreater(len(css), 100)

    def test_contains_css_variables(self):
        css = get_default_css()
        self.assertIn('--tj-primary', css)
        self.assertIn('--tj-header-bg', css)

    def test_contains_table_styles(self):
        css = get_default_css()
        self.assertIn('.tj_report_table', css)
        self.assertIn('border-collapse', css)

    def test_contains_alert_colors(self):
        css = get_default_css()
        self.assertIn('.alert-green', css)
        self.assertIn('.alert-yellow', css)
        self.assertIn('.alert-red', css)

    def test_contains_print_styles(self):
        css = get_default_css()
        self.assertIn('@media print', css)


class TestBuildHtmlDocument(unittest.TestCase):
    def test_basic_document(self):
        html = build_html_document(
            title="Test Report",
            content="<p>Hello World</p>"
        )
        self.assertIn('<!DOCTYPE html>', html)
        self.assertIn('<title>Test Report</title>', html)
        self.assertIn('<p>Hello World</p>', html)

    def test_with_project_name(self):
        html = build_html_document(
            title="Test Report",
            content="<p>Content</p>",
            project_name="My Project"
        )
        self.assertIn('My Project', html)
        self.assertIn('tj_page_header', html)

    def test_with_subtitle(self):
        html = build_html_document(
            title="Test Report",
            content="<p>Content</p>",
            project_name="My Project",
            subtitle="2023-01-01 - 2023-12-31"
        )
        self.assertIn('2023-01-01 - 2023-12-31', html)
        self.assertIn('subtitle', html)

    def test_with_navigation(self):
        nav = [
            {'title': 'Tasks', 'url': 'tasks.html', 'active': True},
            {'title': 'Resources', 'url': 'resources.html', 'active': False}
        ]
        html = build_html_document(
            title="Test Report",
            content="<p>Content</p>",
            navigation=nav
        )
        self.assertIn('tj_navigation', html)
        self.assertIn('tasks.html', html)
        self.assertIn('resources.html', html)
        self.assertIn('class="active"', html)

    def test_with_css_included(self):
        html = build_html_document(
            title="Test",
            content="<p>Content</p>",
            include_css=True
        )
        self.assertIn('<style>', html)
        self.assertIn('--tj-primary', html)

    def test_without_css(self):
        html = build_html_document(
            title="Test",
            content="<p>Content</p>",
            include_css=False
        )
        self.assertNotIn('--tj-primary', html)

    def test_with_custom_css(self):
        html = build_html_document(
            title="Test",
            content="<p>Content</p>",
            custom_css=".my-class { color: red; }"
        )
        self.assertIn('.my-class { color: red; }', html)

    def test_with_footer(self):
        html = build_html_document(
            title="Test",
            content="<p>Content</p>",
            footer=True
        )
        self.assertIn('tj_page_footer', html)
        self.assertIn('Generated by Rodmena Resource Management', html)

    def test_without_footer(self):
        html = build_html_document(
            title="Test",
            content="<p>Content</p>",
            footer=False
        )
        # The CSS still contains .tj_page_footer, but the actual footer element should be absent
        self.assertNotIn('Generated by Rodmena Resource Management', html)

    def test_has_viewport_meta(self):
        html = build_html_document(title="Test", content="<p>Content</p>")
        self.assertIn('viewport', html)
        self.assertIn('width=device-width', html)

    def test_has_charset(self):
        html = build_html_document(title="Test", content="<p>Content</p>")
        self.assertIn('charset="UTF-8"', html)


class TestFormatDate(unittest.TestCase):
    def test_default_format(self):
        dt = datetime(2023, 5, 15)
        result = format_date(dt)
        self.assertEqual(result, '2023-05-15')

    def test_custom_format(self):
        dt = datetime(2023, 5, 15)
        result = format_date(dt, '%d/%m/%Y')
        self.assertEqual(result, '15/05/2023')

    def test_none_returns_empty(self):
        result = format_date(None)
        self.assertEqual(result, '')

    def test_with_time(self):
        dt = datetime(2023, 5, 15, 14, 30)
        result = format_date(dt, '%Y-%m-%d %H:%M')
        self.assertEqual(result, '2023-05-15 14:30')


class TestFormatDuration(unittest.TestCase):
    def test_hours_unit(self):
        result = format_duration(8.5, 'hours')
        self.assertEqual(result, '8.5h')

    def test_days_unit(self):
        result = format_duration(16.0, 'days')
        self.assertEqual(result, '2.0d')

    def test_weeks_unit(self):
        result = format_duration(80.0, 'weeks')
        self.assertEqual(result, '2.0w')

    def test_default_unit_is_days(self):
        result = format_duration(24.0)
        self.assertEqual(result, '3.0d')

    def test_none_returns_empty(self):
        result = format_duration(None)
        self.assertEqual(result, '')

    def test_unknown_unit_defaults_to_hours(self):
        result = format_duration(4.0, 'unknown')
        self.assertEqual(result, '4.0h')


class TestFormatPercentage(unittest.TestCase):
    def test_whole_number(self):
        result = format_percentage(75.0)
        self.assertEqual(result, '75%')

    def test_rounds_to_whole(self):
        result = format_percentage(33.33)
        self.assertEqual(result, '33%')

    def test_none_returns_empty(self):
        result = format_percentage(None)
        self.assertEqual(result, '')


class TestAlertIndicatorHtml(unittest.TestCase):
    def test_green_indicator(self):
        html = alert_indicator_html('green')
        self.assertIn('alert-indicator', html)
        self.assertIn('green', html)

    def test_yellow_indicator(self):
        html = alert_indicator_html('Yellow')
        self.assertIn('alert-indicator', html)
        self.assertIn('yellow', html)

    def test_red_indicator(self):
        html = alert_indicator_html('RED')
        self.assertIn('alert-indicator', html)
        self.assertIn('red', html)

    def test_default_is_green(self):
        html = alert_indicator_html(None)
        self.assertIn('green', html)


class TestJournalEntryHtml(unittest.TestCase):
    class MockEntry:
        def __init__(self):
            self.date = datetime(2023, 5, 15, 10, 30)
            self.headline = "Test Entry"
            self.summary = None

    class MockEntryWithAlert:
        def __init__(self):
            self.date = datetime(2023, 5, 15)
            self.headline = "Alert Entry"
            self.summary = "This is a summary"
            from rodmena_resource_management.core.journal import AlertLevel
            self.alert_level = AlertLevel.YELLOW

    class MockEntryWithAuthor:
        def __init__(self):
            self.date = datetime(2023, 5, 15)
            self.headline = "Authored Entry"
            self.summary = None
            class Author:
                name = "John Doe"
            self.author = Author()

    def test_basic_entry(self):
        entry = self.MockEntry()
        html = journal_entry_html(entry)
        self.assertIn('tj_journal_entry', html)
        self.assertIn('Test Entry', html)
        self.assertIn('2023-05-15', html)

    def test_entry_with_alert(self):
        entry = self.MockEntryWithAlert()
        html = journal_entry_html(entry)
        self.assertIn('alert-yellow', html)
        self.assertIn('This is a summary', html)

    def test_entry_with_author(self):
        entry = self.MockEntryWithAuthor()
        html = journal_entry_html(entry)
        self.assertIn('John Doe', html)
        self.assertIn('tj_journal_author', html)


if __name__ == '__main__':
    unittest.main()
