#!/bin/bash
# Generate EXAM.md for audit team certification
# Contains all test files + their generated reports

set -e

OUTPUT_FILE="EXAM.md"
TEST_DIR="tests/data"

echo "Generating EXAM.md for audit team..."
echo ""

# Start the EXAM.md file
cat > "$OUTPUT_FILE" << 'EOF'
# ScriptPlan Report Generation - Certification Exam

**Generated**: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
**Tool**: plan (ScriptPlan CLI)
**Purpose**: Audit certification of report generation correctness

This document contains all test project files (.tjp) and their corresponding
generated reports (JSON format) for verification and certification.

---

## Table of Contents

EOF

# First pass: generate table of contents
echo "Building table of contents..."
INDEX=1
for tjp_file in "$TEST_DIR"/*.tjp; do
    if [ -f "$tjp_file" ]; then
        filename=$(basename "$tjp_file")
        echo "$INDEX. [$filename](#test-$INDEX-$filename)" >> "$OUTPUT_FILE"
        INDEX=$((INDEX + 1))
    fi
done

echo "" >> "$OUTPUT_FILE"
echo "---" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Second pass: generate content
echo "Generating reports for each test file..."
INDEX=1
TOTAL_FILES=$(find "$TEST_DIR" -name "*.tjp" -type f | wc -l)

for tjp_file in "$TEST_DIR"/*.tjp; do
    if [ -f "$tjp_file" ]; then
        filename=$(basename "$tjp_file")
        echo "[$INDEX/$TOTAL_FILES] Processing $filename..."

        # Generate section header
        cat >> "$OUTPUT_FILE" << EOF

## Test $INDEX: $filename

**File**: \`$tjp_file\`
**Size**: $(stat -f%z "$tjp_file" 2>/dev/null || stat -c%s "$tjp_file") bytes
**Lines**: $(wc -l < "$tjp_file") lines

### Input File Content

\`\`\`tjp
EOF

        # Add the .tjp file content
        cat "$tjp_file" >> "$OUTPUT_FILE"

        # Close the tjp code block
        echo '```' >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"

        # Generate the report
        echo "### Generated Report (JSON)" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"

        # Run plan report and capture output
        if plan report "$tjp_file" 2>/dev/null > /tmp/report_output.json; then
            # Get report metadata
            REPORT_ID=$(jq -r '.report_id' /tmp/report_output.json 2>/dev/null || echo "N/A")
            COLUMN_COUNT=$(jq -r '.columns | length' /tmp/report_output.json 2>/dev/null || echo "N/A")
            ROW_COUNT=$(jq -r '.data | length' /tmp/report_output.json 2>/dev/null || echo "N/A")

            cat >> "$OUTPUT_FILE" << EOF
**Report ID**: \`$REPORT_ID\`
**Columns**: $COLUMN_COUNT
**Rows**: $ROW_COUNT
**Status**: ✓ Success

\`\`\`json
EOF
            # Add formatted JSON
            jq '.' /tmp/report_output.json >> "$OUTPUT_FILE"
            echo '```' >> "$OUTPUT_FILE"
        else
            # Report generation failed
            cat >> "$OUTPUT_FILE" << EOF
**Status**: ✗ Failed

\`\`\`
Error: Report generation failed for this file
EOF
            if plan report "$tjp_file" 2>&1 | head -20 > /tmp/error_output.txt; then
                cat /tmp/error_output.txt >> "$OUTPUT_FILE"
            fi
            echo '```' >> "$OUTPUT_FILE"
        fi

        echo "" >> "$OUTPUT_FILE"
        echo "---" >> "$OUTPUT_FILE"

        INDEX=$((INDEX + 1))
    fi
done

# Add summary section
cat >> "$OUTPUT_FILE" << EOF

## Summary

**Total Test Files**: $TOTAL_FILES
**Generated**: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
**Tool Version**: $(plan --version 2>/dev/null || echo "Unknown")

### Verification Checklist

- [ ] All .tjp files parsed successfully
- [ ] All reports contain valid JSON
- [ ] All report_id fields contain SHA256 hashes
- [ ] All column names are lowercase
- [ ] No HTML metadata in JSON output
- [ ] Data structure matches: \`{data: [...], columns: [...], report_id: "..."}\`

### Notes for Audit Team

This document was automatically generated by the ScriptPlan certification script.
Each test case shows:

1. **Input**: Complete .tjp project file content
2. **Output**: JSON report generated by \`plan report\` command
3. **Metadata**: Report ID (SHA256 hash), column count, row count

To verify correctness, the audit team can:

1. Re-run any test: \`plan report tests/data/<filename>.tjp\`
2. Compare output against this document
3. Verify report_id matches SHA256 of input file: \`sha256sum tests/data/<filename>.tjp\`
4. Validate JSON structure and data completeness

---

**End of Certification Exam Document**
EOF

# Clean up temp files
rm -f /tmp/report_output.json /tmp/error_output.txt

echo ""
echo "✓ EXAM.md generated successfully!"
echo "  File: $OUTPUT_FILE"
echo "  Test files processed: $TOTAL_FILES"
echo "  Size: $(stat -f%z "$OUTPUT_FILE" 2>/dev/null || stat -c%s "$OUTPUT_FILE") bytes"
echo ""
echo "You can now send EXAM.md to the audit team for certification."
